# fly.toml app configuration file generated for queue-teologia-morning-frost-792 on 2025-05-22T02:34:25-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'queue-teologia-morning-frost-792'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
