# fly.toml app configuration file generated for queue-teologia-morning-frost-792 on 2025-05-22T02:34:25-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'queue-teologia-morning-frost-792'
primary_region = 'gig'

[build]


[experimental]
  auto_stop_machines = "never"

[processes]
  worker = "ts-node src/worker.ts"

[[vm]]
  size = 'shared-cpu-2x'
